name: Install Tools & Dependencies
description: Installs Node.js and package dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc

    - name: Install Dependencies
      run: npm ci
      shell: bash
